//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.custorders = new HashSet<custorder>();
        }
    
        public int custID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phonenum { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<custorder> custorders { get; set; }
    }
}
