//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayoff
    {
        public int dayoffID { get; set; }
        public int staff_dayoff_ID { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual staff_dayoff staff_dayoff { get; set; }
    }
}
