//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_admin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<applyforrental> applyforrentals { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<custorder> custorders { get; set; }
        public DbSet<orderproduct> orderproducts { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<showcase> showcases { get; set; }
        public DbSet<showcase_product> showcase_product { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<staff_attendance> staff_attendance { get; set; }
        public DbSet<tenant> tenants { get; set; }
    }
}
