//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class showcase_product
    {
        public int showcase_product_ID { get; set; }
        public int showcaseID { get; set; }
        public int productID { get; set; }
        public System.DateTime stockInDate { get; set; }
        public int stockInQty { get; set; }
    
        public virtual product product { get; set; }
        public virtual showcase showcase { get; set; }
    }
}
