//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_dayoff
    {
        public staff_dayoff()
        {
            this.dayoffs = new HashSet<dayoff>();
        }
    
        public int staff_dayoff_ID { get; set; }
        public int staffID { get; set; }
        public short year { get; set; }
        public int month { get; set; }
    
        public virtual ICollection<dayoff> dayoffs { get; set; }
        public virtual staff staff { get; set; }
    }
}
