//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public attendance()
        {
            this.staff_attendance = new HashSet<staff_attendance>();
        }
    
        public int attendanceID { get; set; }
        public int staffID { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan basicPunchIn { get; set; }
        public System.TimeSpan basicPunchOut { get; set; }
        public System.TimeSpan punchIn { get; set; }
        public System.TimeSpan punchOut { get; set; }
    
        public virtual ICollection<staff_attendance> staff_attendance { get; set; }
    }
}
