//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderproduct
    {
        public int order_product_ID { get; set; }
        public int orderID { get; set; }
        public int productID { get; set; }
        public int orderQTY { get; set; }
    
        public virtual custorder custorder { get; set; }
        public virtual product product { get; set; }
    }
}
