//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class showcase
    {
        public showcase()
        {
            this.applyrentals = new HashSet<applyrental>();
            this.showcase_product = new HashSet<showcase_product>();
        }
    
        public int showcaseID { get; set; }
        public int rentCost { get; set; }
        public string status { get; set; }
        public string location { get; set; }
    
        public virtual ICollection<applyrental> applyrentals { get; set; }
        public virtual ICollection<showcase_product> showcase_product { get; set; }
    }
}
