//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.staff_attendance = new HashSet<staff_attendance>();
        }
    
        public int staffID { get; set; }
        public string fulltime_parttime { get; set; }
        public string staff_admin { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int phonenumber { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int salary { get; set; }
        public System.TimeSpan basicPunchIn { get; set; }
        public System.TimeSpan basicPunchOut { get; set; }
    
        public virtual ICollection<staff_attendance> staff_attendance { get; set; }
    }
}
