//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenant
    {
        public tenant()
        {
            this.applyrentals = new HashSet<applyrental>();
        }
    
        public int tenantID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int phonenumber { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<applyrental> applyrentals { get; set; }
    }
}
